kind: Pod
apiVersion: v1
metadata:
  name: fast-data-dev
spec:
  containers:
    - name: fast-data-dev
      image: landoop/fast-data-dev
      env:
        - name: ADV_HOST
          value: fast-data-dev
      ports:
        - containerPort: 2181
        - containerPort: 3030
        - containerPort: 8081
        - containerPort: 8082
        - containerPort: 9092