kind: Service
apiVersion: v1
metadata:
  name: fast-data-dev
spec:
  selector:
    app: fast-data-dev
  ports:
  - name: "zookeeper"
    port: 2181
    targetPort: 2181
  - name: "port3030"
    port: 3030
    targetPort: 3030
  - name: "port8081"
    port: 8081
    targetPort: 8081
  - name: "port8082"
    port: 8082
    targetPort: 8082
  - name: "kafka"
    port: 9092
    targetPort: 9092