kind: Pod
apiVersion: v1
metadata:
  name: mongo
spec:
  volumes:
    - name: mongo-pv-storage
      persistentVolumeClaim:
        claimName: mongodb-pv-claim
  containers:
    - name: mongodb
      image: mongo
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
      ports:
        - containerPort: 27017
          name: "mongo-server"
      volumeMounts:
        - mountPath: "/data/db"
          name: mongo-pv-storage