kind: Service
apiVersion: v1
metadata:
  name: mqtt-kafka
spec:
  selector:
    app: mqtt-kafka
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mqtt-kafka-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mqtt-kafka
  template:
    metadata:
      labels:
        app: mqtt-kafka
    spec:
      containers:
        - name: mqtt-kafka
          image: mqtt-kafka:0.5
          env:
            - name: KAFKA_BROKER_URI
              value: "kafka-server:9092"
            - name: MQTT_SERVER_URI
              value: "mqtt-server:1883"
