kind: Deployment
apiVersion: apps/v1
metadata:
  name: nifi-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          image: apache/nifi
          ports:
            - containerPort: 8080